GET http://localhost:5000/admin

###
GET http://localhost:5000/admin/3

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "nama":"Palmia",
    "perioda" :"2015-04-03 14:00:45",
    "harga":25000,
    "stok":50
}

###
PATCH http://localhost:5000/admin/2
Content-Type: application/json

{
    "nama":"Palmia Premium",
    "perioda" :"2022-04-03 14:00:45",
    "harga":25000,
    "stok":50
}
###
DELETE http://localhost:5000/admin/2


# ***USERS
###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/7

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"kok eror",
    "password" :"12345",
    "status" :"rw"
}

###
PATCH http://localhost:5000/users/4
Content-Type: application/json

{
    "username":"gasta ubah",
    "password" :"12345",
    "status" :"rw"
}
###
DELETE http://localhost:5000/users/4


###
GET http://localhost:5000/domisili

###
GET http://localhost:5000/domisili/3

###
POST http://localhost:5000/domisili
Content-Type: application/json

{
    "kecamatan":"Cisarua",
    "kelurahan":"Lama"
}

###
PATCH http://localhost:5000/domisili/2
Content-Type: application/json

{
    "kecamatan":"Antapani",
    "kelurahan":"Antapani Baru"
}

###
DELETE http://localhost:5000/domisili/1